### ISSUE TITLE
Overriding method at New component

### ISSUE THREAD

**Issue by giovanisleite** [SeasonedSoftware/croods#30]
Situation:

I can't use `Edit` because the Info is not available.
I can't use `Update` because I need what the endpoint returns.

The options are overwrite the method of `New` from POST to PUT or Add an option to have a renderUpdated on the Update.

**Comment by felipefreitag** [comment]
For clarity: in this case, there isn't a `Info` endpoint.

**Comment by giovanisleite** [comment]
Closed by #31
