### ISSUE TITLE
If there's an error at an Info, when I change the id, the error is still there even though it relates to another object.

### ISSUE THREAD

**Issue by felipefreitag** [SeasonedSoftware/croods#32]

**Comment by gustavoguichard** [comment]
@felipefreitag I could not replicate this problem. On the croods sample page I changed the Info code to have an invalid ID and then get a valid one after 3 seconds according to this code:
```
const [id, setid] = useState('foobar')
  useEffect(() => {
    setTimeout(() => {
      setid(givenId)
    }, 3000)
  }, [])
```

But the result does not seem to disappoint :
![demo](https://user-images.githubusercontent.com/566971/113622088-dfab2a80-9632-11eb-893d-338043d577f9.gif)

Where am I missing your point here?

**Comment by felipefreitag** [comment]
I don't remember anymore. Better to use #dev-help to see what's going on recently.
