### ISSUE TITLE
query option should convert its properties to snake_case

### ISSUE THREAD

**Issue by danielweinmann** [SeasonedSoftware/croods#33]

**Comment by gustavoguichard** [comment]
@danielweinmann , are you talking about https://croods.netlify.com/docs/fetch-api#query ?

Otherwise, have you seen these?
- [paramsParser](https://croods.netlify.com/docs/croods-provider-api#paramsparser)
- [paramsUnparser](https://croods.netlify.com/docs/croods-provider-api#paramsunparser)

**Comment by gustavoguichard** [comment]
@danielweinmann , can I close this issue?

**Comment by danielweinmann** [comment]
Sure
