### ISSUE TITLE
After a failure the info/list should be cleaned

### ISSUE THREAD

**Issue by giovanisleite** [SeasonedSoftware/croods#48]

**Comment by felipefreitag** [comment]
Where was this an issue?

**Comment by giovanisleite** [comment]
SavedGuides in Supersummary

The user visited a saved guide, the info was filled, when he visited another guide, the request failed but the info about the request that was successful remained there, so info and error had data.

**Comment by felipefreitag** [comment]
Isn't that solved by adding a `stateId` to SavedGuides?

**Comment by giovanisleite** [comment]
Yes, but this is a problem when it keeps the same statedId and the second request fails

**Comment by felipefreitag** [comment]
Not sure if the desired behavior would be to clear the stale data. It might be better to have stale data than to lose it, I think it depends on the situation.

**Comment by gustavoguichard** [comment]
I agree with @felipefreitag on this one, a "one project need" should not drive the design of croods unless it becomes a pattern.
This can be easily addressed with:
```js
const [, { setInfo, setList }] = useCroods({
  name: 'foo',
  id: 1,
  afterFailure: () => {
    setInfo(null)
    setList([])
  }
})
```

I'll close the isse, @giovanisleite, but feel free to raise it again if you still think this should be discussed further ;)
